"use strict";
const fs = require('fs');
async function only(nyz, satzz, from) {  
if (nyz == "isGroup") { satzz.sendMessage(from, {sticker:{url:"https://raw.githubusercontent.com/naylachan/STICKER/main/onlygroup.webp"}},{quoted:{ key: {fromMe: false, participant: `0@s.whatsapp.net`, ...(from ? { remoteJid: "status@broadcast" } : {})},message: {"conversation": "[ *INFO* ] GUNAKAN DI GROUP!"}}  })}
if (nyz == "isGroupAdmins") { satzz.sendMessage(from, {sticker:{url:"https://raw.githubusercontent.com/naylachan/STICKER/main/onlyadmin.webp"}},{quoted:{ key: {fromMe: false, participant: `0@s.whatsapp.net`, ...(from ? { remoteJid: "status@broadcast" } : {})},message: {"conversation": "[ *INFO* ] KAMU BUKAN ADMIN!"}}  })}
if (nyz == "isOwner") { satzz.sendMessage(from, { audio: fs.readFileSync('./media/gamau.mp3'), mimetype: 'audio/mp4', ptt: true},{quoted:{ key: {fromMe: false, participant: `0@s.whatsapp.net`, ...(from ? { remoteJid: "status@broadcast" } : {})},message: {"conversation": "[ *INFO* ] KAMU BUKAN OWNER!"}}  })}
if (nyz == "isBotGroupAdmins") { satzz.sendMessage(from, {sticker:{url:"https://raw.githubusercontent.com/naylachan/STICKER/main/botadmin.webp"}},{quoted:{ key: {fromMe: false, participant: `0@s.whatsapp.net`, ...(from ? { remoteJid: "status@broadcast" } : {})},message: {"conversation": "[ *INFO* ] BOT BUKAN ADMIN!"}}  })}
if (nyz == "error") { satzz.sendMessage(from, {sticker:{url:"https://raw.githubusercontent.com/naylachan/STICKER/main/error.webp"}},{quoted:{ key: {fromMe: false, participant: `0@s.whatsapp.net`, ...(from ? { remoteJid: "status@broadcast" } : {})},message: {"conversation": "[ *INFO* ] COBA LAGI NANTI!"}}  })}
if (nyz == "sukses") { satzz.sendMessage(from, {sticker:{url:"https://raw.githubusercontent.com/naylachan/STICKER/main/sukses.webp"}},{quoted:{ key: {fromMe: false, participant: `0@s.whatsapp.net`, ...(from ? { remoteJid: "status@broadcast" } : {})},message: {"conversation": "[ *INFO* ] STATUS SUKSES!"}}  })}
if (nyz == "proses") { satzz.sendMessage(from, { audio: fs.readFileSync('./media/cepetan.mp3'), mimetype: 'audio/mp4', ptt: true},{quoted:{ key: {fromMe: false, participant: `0@s.whatsapp.net`, ...(from ? { remoteJid: "status@broadcast" } : {})},message: {"conversation": "[ *INFO* ] TUNGGU SEBENTAR!"}}  })}
if (nyz == "antilink") { satzz.sendMessage(from, {sticker:{url:"https://raw.githubusercontent.com/naylachan/STICKER/main/antilink.webp"}},{quoted:{ key: {fromMe: false, participant: `0@s.whatsapp.net`, ...(from ? { remoteJid: "status@broadcast" } : {})},message: {"conversation": "[ *INFO* ] LINK DETEKSI!"}}  })}
} 
module.exports = { only }